name: build-project
on: 
  push:
    branches: main
  pull_request:

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup Java
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2.5.0
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup and execute Gradle build
      uses: gradle/gradle-build-action@v2.0.1
      with:
        arguments: build
        arguements: check --scan
